name: sin-app

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sinuser
      POSTGRES_PASSWORD: sinpassword
      POSTGRES_DB: sindb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sinproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sinuser -d sindb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Server
      target: production
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Server/.env
    networks:
      - sinproject
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./Client
      target: production
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Client/.env
    networks:
      - sinproject
    depends_on:
      - api
  
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sinproject
    depends_on:
      - api 
      - client

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  sinproject:
    driver: bridge
