name: Sinproject-app
x-build-dns: &build-dns
  dns:
    - 8.8.8.8
    - 8.8.4.4
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sinuser
      POSTGRES_PASSWORD: sinpassword
      POSTGRES_DB: sindb
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - sinproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sinuser -d sindb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Server
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - sinproject
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm ci --include=dev && npm run dev"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  client:
    build:
      context: ./Client
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./Client/.env
    volumes:
      - ./Client:/app
      - /app/node_modules
    networks:
      - sinproject
    depends_on:
      - api
    ports:
      - "5173:5173"

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sinproject
    depends_on:
      - client

volumes:
  caddy_data:
  caddy_config:
  db_data_dev:
networks:
  sinproject:
    driver: bridge
