name: sin-app

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sin-app
    
  api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
      - api_logs:/app/logs
    networks:
      - sin-app
    depends_on:
      - db

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Client/.env
    volumes:
      - ./Client:/app
      - /app/node_modules
    networks:
      - sin-app
    depends_on:
      - api

volumes:
  db_data:
  api_logs:

networks:
  sin-app:
    driver: bridge